# Handling [tensors](https://pytorch.org/docs/stable/tensors.html?highlight=tensor#torch.Tensor) with PyTorch
At its core, PyTorch is a library that provides multidimensional arrays, called tensors in
PyTorch parlance, and an extensive library of operations on them is provided by the torch module. Both tensors and related operations can run on the CPU or GPU. The second core thing that PyTorch allows tensors to keep track of the operations performed on them and to compute derivatives of an output with respect to any of its inputs analytically via backpropagation.

**Key points**

- Numbers in Python are full-fledged objects.
- Lists in Python are meant for sequential collections of objects.
- The Python interpreter is slow compared with optimized, compiled code

![memory](./images/memory.png)

PyTorch tensors or NumPy arrays, on the other hand, are views over (typically) contiguous memory blocks containing unboxed C numeric types, not Python objects. So a 1D tensor of 1 million float numbers requires 4 million contiguous bytes to be stored, plus a small overhead for the metadata (dimensions, numeric type, and so on).



In [43]:
import numpy as np
import torch
print(torch.__version__) 

1.4.0


### Pytorch-Numpy interoperability

Values are allocated in contiguous chunks of memory, managed by torch.Storage instances. A storage is a one-dimensional array of numerical data, such as a contiguous block of memory containing numbers of a given type, perhaps a float or int32. A PyTorch Tensor is a view over such a Storage that’s capable of indexing into that storage by using an offset and per-dimension strides

![storage](./images/storage.png)


Some useful methods:
- .tensor() will make a copy of the argument
- .numpy() will return a view on the same memory elements
- .from_numpy() will return a view on the same memory elements

In [44]:
arr_np = np.random.randn(2, 3)
print("Numpy array:\n{}\n".format(arr_np))

tens = torch.tensor(arr_np) # change printing precision with torch.set_printoptions()
print("Tensor :\n{}\n".format(tens))


print("#####\nWe modify the element (0, 0) of the tensor object")
tens[0, 0] = 10
print("Tensor :\n{}\n".format(tens))
print("Numpy array:\n{}\n".format(arr_np))

Numpy array:
[[ 2.9092417  -0.34150317 -0.65716409]
 [ 2.40865071 -1.06449676 -0.28400444]]

Tensor :
tensor([[ 2.9092, -0.3415, -0.6572],
        [ 2.4087, -1.0645, -0.2840]], dtype=torch.float64)

#####
We modify the element (0, 0) of the tensor object
Tensor :
tensor([[10.0000, -0.3415, -0.6572],
        [ 2.4087, -1.0645, -0.2840]], dtype=torch.float64)

Numpy array:
[[ 2.9092417  -0.34150317 -0.65716409]
 [ 2.40865071 -1.06449676 -0.28400444]]



In [45]:
arr_from_tens = tens.numpy()
print("Numpy array obtained with tens.numpy():\n{}\n".format(arr_from_tens)) # it is a view on the same storage

arr_from_tens[0, 1] = 20
print("Changing this numpy array will change our tensor too:\n{}\n".format(tens))

Numpy array obtained with tens.numpy():
[[10.         -0.34150317 -0.65716409]
 [ 2.40865071 -1.06449676 -0.28400444]]

Changing this numpy array will change our tensor too:
tensor([[10.0000, 20.0000, -0.6572],
        [ 2.4087, -1.0645, -0.2840]], dtype=torch.float64)



With slicing we get different tensor views on the same underlying data. We can get copied pieces of those view as python numbers or lists with tens.item() for single values, or tens.tolist().
To check that they are copies, we can use np.shares_memory()

In [46]:
tens_first_row = tens[0]
tens_element_as_py_obj = tens[0, 0].item()
tens_as_list = tens.tolist()

print(np.shares_memory(tens, tens_first_row))
print(np.shares_memory(tens, tens_element_as_py_obj))
print(np.shares_memory(tens, tens_as_list))

True
False
False


The shape of our tensor is given by the way we strides along the underlying storage

In [47]:
print(tens.size())
print(tens.shape)

torch.Size([2, 3])
torch.Size([2, 3])


### [Factory functions](https://pytorch.org/cppdocs/notes/tensor_creation.html#picking-a-factory-function)

In [48]:
print(torch.randint(0, 10, size=(2, 1)))
print(torch.arange(10))
print(torch.linspace(0, 1, 8))
print(torch.eye(2))
print(torch.zeros(3,3))
print(torch.ones(1, 2))
print(torch.randn(3))
print(torch.randperm(12))

tensor([[6],
        [8]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571, 1.0000])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.]])
tensor([-0.3581,  1.0653, -0.4156])
tensor([ 4,  8, 11, 10,  9,  3,  0,  2,  1,  7,  6,  5])


In [51]:
print(torch.FloatTensor([[1, 0], [0, 1]]))
print(torch.Tensor(2, 3))

tensor([[1., 0.],
        [0., 1.]])
tensor([[6.4429e-11, 3.0970e-41, 4.8653e-14],
        [4.5872e-41, 8.9683e-44, 0.0000e+00]])


torch.empty() allows to construct a tensor without initializing any value. 

We can sample in place from a broader range of distributions by using Tensor's methods.

In [52]:
print(torch.empty(2, 3))
print(torch.empty(3).cauchy_())
print(torch.empty(3).geometric_(0.7))

tensor([[4.8653e-14, 4.5872e-41, 3.0411e+25],
        [3.0970e-41, 4.4842e-44, 0.0000e+00]])
tensor([ 0.4363,  0.6305, -3.3436])
tensor([2., 5., 1.])


Trailing underscore concerns in-place methods, i.e. those methods who transforms the input without making a copy

In [53]:
twotwo = 2 * torch.ones(2)
print(twotwo)

twotwo_sqrt = torch.sqrt(twotwo)
print(twotwo_sqrt)

print(np.shares_memory(twotwo, twotwo_sqrt))

twotwo.sqrt_()
print(twotwo)

tensor([2., 2.])
tensor([1.4142, 1.4142])
False
tensor([1.4142, 1.4142])


### [Numeric types](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and casting
The dtype argument to tensor constructors (that is, functions such as tensor, zeros, and ones) specifies the numerical data type that will be contained in the tensor. The data type specifies the possible values that the tensor can hold (integers versus floating-point numbers) and the number of bytes per value.

torch.Tensor is an alias for the default tensor type, torch.FloatTensor

In [54]:
print(torch.zeros(2).type())
print(torch.tensor([0, 1, 2], dtype=torch.short))
print(torch.tensor([0, 1, 2]).short())

print(torch.ones(3, dtype=torch.double))
print(torch.ones(3).double())

torch.FloatTensor
tensor([0, 1, 2], dtype=torch.int16)
tensor([0, 1, 2], dtype=torch.int16)
tensor([1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1.], dtype=torch.float64)


In addition to the dtype, a PyTorch tensor has a notion of device, which specifies if the operations on that tensor will be carried out by the CPU or a GPU, if one is present on the machine

In [56]:
print(torch.ones(3, device='cuda'))
print(torch.ones(3).cuda())
print(torch.ones(3).to('cuda'))

print(torch.ones(3).to('cuda').type())

tensor([1., 1., 1.], device='cuda:0')
tensor([1., 1., 1.], device='cuda:0')
tensor([1., 1., 1.], device='cuda:0')
torch.cuda.FloatTensor


## Operations on tensors

In [57]:
a = torch.randn(3, 1)
b = torch.randn_like(a)

print("a + b = {}".format(a + b))

a + b = tensor([[ 1.9529],
        [-0.5510],
        [ 1.7504]])


In [58]:
# about ampersand operator: https://www.python.org/dev/peps/pep-0465/
print("a @ b.T = {}".format(a @ b.T))

a @ b.T = tensor([[-0.5916, -0.2719, -0.5495],
        [-3.4866, -1.6023, -3.2385],
        [-0.6904, -0.3173, -0.6412]])


In [59]:
# dimensions inversion
print("a.T = {}".format(a.T))

a.T = tensor([[-0.2665, -1.5710, -0.3111]])


In [60]:
# matrix transpose (https://pytorch.org/docs/stable/tensors.html#torch.Tensor.t)
print("a.t() = {}".format(a.t()))

a.t() = tensor([[-0.2665, -1.5710, -0.3111]])


In [61]:
c = torch.randint(0, 10, size=(2, 3, 4, 5, 6))
print(c.size())
print(c.T.size())
print(c.transpose(0, 2).size())
# print(c.t().size()) # error

torch.Size([2, 3, 4, 5, 6])
torch.Size([6, 5, 4, 3, 2])
torch.Size([4, 3, 2, 5, 6])


In [62]:
print(c.dim()) # the order of the tensor
print(c.numel())
print(torch.numel(c))

5
720
720


In [63]:
d = torch.tensor([[0, 1], [2, 467]])
print(d)

tensor([[  0,   1],
        [  2, 467]])


In [65]:
print(d.view(-1, 4))

tensor([[  0,   1,   2, 467]])


In [66]:
print(d.dim())

2


In [67]:
print(d.unsqueeze(0).size())

torch.Size([1, 2, 2])


In [68]:
print(d.squeeze(0))
print(d.fill_(33))

tensor([[  0,   1],
        [  2, 467]])
tensor([[33, 33],
        [33, 33]])


In [69]:
d

tensor([[33, 33],
        [33, 33]])

In [70]:
d.resize_(4)

tensor([33, 33, 33, 33])

In [71]:
e = torch.ones_like(d)
print(torch.cat([d, e], dim=0))

tensor([33, 33, 33, 33,  1,  1,  1,  1])


In [72]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print('Device: {}'.format(device))

Device: cuda:0


The [.to()](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to) method returns a new tensor. We can use it to convert either its type and its device

In [ ]:
e = e.to(device)

### Resources

Pictures from: [Deep Learning with Pytorch - Stevens, Antiga](https://pytorch.org/assets/deep-learning/Deep-Learning-with-PyTorch.pdf)

[Official documentation](https://pytorch.org/docs/stable/index.html)

[Tutorials](https://pytorch.org/tutorials/)

[Nice guy talking about tensors](https://www.youtube.com/watch?v=f5liqUk0ZTw)